### ISSUE TITLE
[kops] Add Support for Extensions

### ISSUE THREAD

**Issue by osterman** [cloudposse/geodesic#240]
## what
```
# Allow the manifest to be extended via a datasource
{{if (datasourceExists "extensions")}}
{{include "extensions"}}
{{end}}
```

## why
* Allow users to extend the manifest

## use-case

Add custom instance pools. 

e.g.

```
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{getenv "KOPS_CLUSTER_NAME"}}
  name: example-nodes
spec:
  detailedInstanceMonitoring: {{ getenv "KOPS_CLOUDWATCH_DETAILED_MONITORING" "true" }}
  {{- if getenv "NODE_IG_SG_IDS" }}
  additionalSecurityGroups:
    {{- range (getenv "NODE_IG_SG_IDS" | strings.Split ",") }}
  - {{.}}
    {{- end }}
  {{- end}}
  associatePublicIp: false
  cloudLabels:
    Role: k8s-vortex-node
  image: {{ getenv "KOPS_BASE_IMAGE" }}
  machineType: {{getenv "EXAMPLE_MACHINE_TYPE"}}
  maxSize: {{getenv "EXAMPLE_MAX_SIZE"}}
  minSize: {{getenv "EXAMPLE_MIN_SIZE"}}
  nodeLabels:
    dedicated: {{getenv "EXAMPLE_LABEL" | default "example" }}
  role: Node
  subnets:
  - {{getenv "AWS_REGION"}}a
  taints:
  - dedicated={{getenv "EXAMPLE_LABEL" | default "example" }}:NoSchedule
```
